#spring.application.name=ComicUAM
#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
#spring.datasource.url=jdbc:mysql://localhost:3306/comicuam?useSSL=false&serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=1234
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.application.name=ComicUAM
<<<<<<< HEAD
spring.datasource.url=jdbc:mysql://localhost:3306/comicuam?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
=======

# Usar base de datos H2 en memoria (No requiere instalar nada)
spring.datasource.url=jdbc:h2:mem:comicuam;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Permitir que Spring cree las tablas automáticamente en la RAM
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
>>>>>>> main
